#I "/Users/alanwostenberg/Projects/FSharp/CircusMaximus/lib/"
#I "/Users/alanwostenberg/Projects/FSharp/CircusMaximus/CircusMaximus/"
#r "MonoGame.Framework.dll"
#load "BasicFunctions/HelperFunctions.fs"
#load "BasicFunctions/Extensions.fs"
#load "BasicFunctions/LinearEquation.fs"
#load "BasicFunctions/LineSegment.fs"
open System
open Microsoft.Xna.Framework
open CircusMaximus.LinearEquation
open CircusMaximus.HelperFunctions
open CircusMaximus.LineSegment